### ISSUE TITLE
Error when running python node

### ISSUE THREAD

**Issue by FlammableTea** [WPI-AIM/ros_falcon#10]
Package compiled correctly, however when I try to launch the node I get the following error: 

Traceback (most recent call last):
  File "joy2cmd_vel.py", line 1, in <module>
    import roslib; roslib.load_manifest('rosfalcon')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 93, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 167, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 211, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: rosfalcon
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share

I tried updating rospkg, and I'm pretty sure my ROS_PACKAGE_PATH is fine, as it returns /home/ubuntu/catkin_ws/src:/opt/ros/kinetic/share

I don't see any similar issues so I get the feeling that I'm doing something wrong but I'm not sure what it is...

**Comment by adnanmunawar** [comment]
I think the issue stems from the package name 'rosfalcon'. Please check the latest commit to see if it fixes this issue.

**Comment by FlammableTea** [comment]
Node launches in the latest commit. Thanks!
